Work around problems with the go version.

diff --git a/ap/barnard/SLKBUILD b/ap/barnard/SLKBUILD
--- a/ap/barnard/SLKBUILD
+++ b/ap/barnard/SLKBUILD
@@ -33,22 +33,11 @@ build() {
     return 1
   fi
 
-  export CGO_CPPFLAGS="${CPPFLAGS}"
-  export CGO_CFLAGS="${CFLAGS}"
-  export CGO_CXXFLAGS="${CXXFLAGS}"
-  export CGO_LDFLAGS="${LDFLAGS}"
-  export GOFLAGS="-buildmode=pie -trimpath -mod=readonly -modcacherw"
-  goTarget="."
-  if [ -d "cmd/$pkgname" ]; then
-    goTarget="./cmd/$pkgname"
-  fi
-  go build "$goTarget"
-
-  if [ ! -f "$pkgname" ]; then
-    echo "Built $pkgname binary not found." >&2
+  if [ ! -f "$startdir/$pkgname" ]; then
+    echo "Prebuilt $pkgname binary not found at $startdir/$pkgname." >&2
     return 1
   fi
-  install -Dm755 "$pkgname" "$PKG/usr/bin/$pkgname"
+  install -Dm755 "$startdir/$pkgname" "$PKG/usr/bin/$pkgname"
 
   if [ -f "$pkgname-ui" ]; then
     install -Dm755 "$pkgname-ui" "$PKG/usr/bin/$pkgname-ui"
